#!/usr/bin/env python3

import argparse
import sys

from cc_pathlib import Path

import cc_pathlib

import unitest.replay

pa = argparse.ArgumentParser(description='replay a given scenario')

pa.add_argument('node_name', metavar='NODE_NAME', help='name of the node to be replayed')
pa.add_argument('replay_dir', metavar='REPLAY_DIR', help='folder holding the input table')

ap = pa.parse_args()

u = unitest.replay.UnitestReplay(ap.node_name, ap.replay_dir).run()
