#!/usr/bin/env python3

import argparse
import sys

from cc_pathlib import Path

import cc_pathlib
print(cc_pathlib.__file__)

import unitest.replay

pa = argparse.ArgumentParser(description='replay a given scenario')

pa.add_argument('node_name', metavar='NODE_NAME', help='name of the node to be replayed')
pa.add_argument('replay_dir', metavar='REPLAY_DIR', help='folder holding the input table')

ap = pa.parse_args()

u = unitest.replay.UnitestReplay(ap.node_name, ap.replay_dir).run()

# u.run_node()

# u.output_to_tsv()
# u.context_to_tsv()

# shortcut_pth = (u.replay_dir.parent / 'context.tsv')
# if shortcut_pth.is_file() :
# 	shortcut_pth.unlink()
# shortcut_pth.hardlink_to(u.replay_dir / 'context.tsv')
